version: '3.8'
services:
  dev-database:
    image: postgres:15.2
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host(myPC)} : {port in container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
  #Create another container for "TEST"
  test-database:
    image: postgres:15.2
    container_name: test-database
    ports:
      - 5435:5432 #{port in host(myPC)} : {port in container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
#Create container, network,... from docker compose file: 
#-d: deamon/background mode
  #docker compose up -d 
#Start only spectified services/container:
  #docker compose up -d dev-database -d
#Romove container + volumes
  #docker compose rm dev-database --stop --force --volumes
